### ISSUE TITLE
potential memory leak: forgetting to free error message of libsqlite3 API 'sqlite3_exec'

### ISSUE THREAD

**Issue by Zero0one1** [jefferis/cmtk#3]
According to libsqlite3 API document, "To avoid memory leaks, the application should invoke sqlite3_free() on error message strings returned through the 5th parameter of sqlite3_exec() after the error message string is no longer needed."

https://github.com/jefferis/cmtk/blob/c481a075b21826d9636400c9b07c118bdec3c29d/core/Utilities/sqlite3/shell.c#L2681-L2684

**Comment by jefferis** [comment]
Thank you. Since this in the sqlite3 codebase itself and more specifically in the shell tool, which cmtk does not use, I think we can safely ignore.
